version: "2"
services:
  be-docker: 
    image: guyalondocker/be-docker
    ports: 
      - 80:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://docker:docker@localhost:5432/twitter
      - PORT=3000   
  db:
    image: postgres:10.4
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=twitter
   
