version: "2"
services:
  be-docker: 
    image: guyalondocker/be-docker
    ports: 
      - 80:3000
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm start'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgrespass@localhost:5432/twitter
      - PORT=3000   
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespass
      - POSTGRES_DB=twitter
    command: ["psql","-U","postgres","-d","twitter","-a","-f","twitter.sql"]

